import { Activity, ActivityCategory, UserRole, User, Review, Reward } from './types';

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    activityId: '101',
    activityTitle: 'Campus Marathon 2023',
    rating: 5,
    content: 'Great atmosphere and well organized!',
    timestamp: '2023-11-15'
  },
  {
    id: 'r2',
    activityId: '102',
    activityTitle: 'Python Workshop',
    rating: 4,
    content: 'Very informative but a bit fast-paced.',
    timestamp: '2024-03-10'
  }
];

export const MOCK_REWARDS: Reward[] = [
  { id: 'rw1', title: 'PKU Coffee Voucher', cost: 100, icon: '☕', description: 'Redeem for a free coffee at any campus cafe.' },
  { id: 'rw2', title: 'Library Fast Pass', cost: 500, icon: '📚', description: 'Skip the queue for study room booking for one week.' },
  { id: 'rw3', title: 'Limited Edition Badge', cost: 300, icon: '🎖️', description: 'Exclusive 126th Anniversary metal badge.' },
  { id: 'rw4', title: 'Gym Access Card', cost: 200, icon: '💪', description: 'One-time entry to Khoo Teck Puat Gym.' },
];

export const MOCK_USER: User = {
  name: "Alex Zhang",
  role: UserRole.GRADUATE,
  preferences: [ActivityCategory.ACADEMIC, ActivityCategory.CAREER],
  joinedActivities: ['1', '3', '6', '8'], // IDs of upcoming activities
  savedActivities: ['2'],
  completedActivities: ['101', '102'], // IDs of past activities
  redeemedRewards: [],
  points: 340,
  reviews: MOCK_REVIEWS
};

// Hardcoded Data Set (Simulating "Code Upload")
export const ACTIVITIES: Activity[] = [
  {
    id: '1',
    title: "人工智能前沿讲座：大模型时代",
    titleEn: "Frontiers in AI: The Era of Large Models",
    organizer: "School of Intelligence Science",
    date: "2024-05-20",
    time: "14:00 - 16:00",
    location: "二教 101 (Teaching Bldg 2, Room 101)",
    category: ActivityCategory.ACADEMIC,
    description: "本次讲座邀请了图灵奖得主进行分享，深入探讨Transformer架构的未来演进以及AGI的可能性。适合计算机及相关专业研究生参加。",
    descriptionEn: "Invited lecture by Turing Award winner discussing the future evolution of Transformer architecture and the possibilities of AGI. Suitable for CS graduates.",
    image: "https://picsum.photos/400/250?random=1",
    tags: ["AI", "Lecture", "Academic"],
    registeredCount: 150,
    maxCapacity: 200,
    status: 'upcoming'
  },
  {
    id: '2',
    title: "周末桌游之夜：破冰与策略",
    titleEn: "Weekend Board Game Night: Icebreaker & Strategy",
    organizer: "Board Game Association",
    date: "2024-05-21",
    time: "19:00 - 22:00",
    location: "新太阳中心 B102 (New Sun Center B102)",
    category: ActivityCategory.SOCIAL,
    description: "不论你是桌游萌新还是策略老手，都欢迎加入我们！提供狼人杀、阿瓦隆、卡坦岛等多种游戏。提供免费零食饮料。",
    descriptionEn: "Whether you are a newbie or a pro, join us! Werewolf, Avalon, Catan and more available. Free snacks and drinks provided.",
    image: "https://picsum.photos/400/250?random=2",
    tags: ["Fun", "Social", "Relax"],
    registeredCount: 12,
    maxCapacity: 30,
    status: 'upcoming'
  },
  {
    id: '3',
    title: "中国传统书法体验工作坊",
    titleEn: "Traditional Chinese Calligraphy Workshop",
    organizer: "International Students Division",
    date: "2024-05-22",
    time: "15:00 - 17:00",
    location: "勺园 3号楼 (Shaoyuan Bldg 3)",
    category: ActivityCategory.CULTURE,
    description: "专为留学生设计的书法体验课。由艺术学院老师手把手教学，体验墨香韵味。提供所有书写工具。",
    descriptionEn: "A calligraphy workshop designed for international students. Taught by Art School professors. All tools provided.",
    image: "https://picsum.photos/400/250?random=3",
    tags: ["Culture", "Art", "International Friendly"],
    registeredCount: 45,
    maxCapacity: 50,
    status: 'upcoming'
  },
  {
    id: '4',
    title: "秋季名企实习双选会",
    titleEn: "Autumn Internship Fair",
    organizer: "Career Center",
    date: "2024-05-25",
    time: "09:00 - 17:00",
    location: "邱德拔体育馆 (Khoo Teck Puat Gym)",
    category: ActivityCategory.CAREER,
    description: "汇集腾讯、字节跳动、中金等百余家名企，提供暑期实习与全职岗位。请携带简历入场。",
    descriptionEn: "Featuring Tencent, ByteDance, CICC and 100+ top companies. Summer internships and full-time jobs. Please bring your resume.",
    image: "https://picsum.photos/400/250?random=4",
    tags: ["Job", "Internship", "Career"],
    registeredCount: 500,
    maxCapacity: 1000,
    status: 'upcoming'
  },
  {
    id: '5',
    title: "未名湖晨跑团",
    titleEn: "Weiming Lake Morning Run Club",
    organizer: "Running Association",
    date: "2024-05-26",
    time: "06:30 - 07:30",
    location: "未名湖石鱼 (Stone Fish, Weiming Lake)",
    category: ActivityCategory.SPORTS,
    description: "迎着朝阳，环湖慢跑。适合所有配速的跑者。跑完一起吃早饭！",
    descriptionEn: "Morning jog around the lake at sunrise. All paces welcome. Breakfast together afterwards!",
    image: "https://picsum.photos/400/250?random=5",
    tags: ["Sports", "Health", "Outdoor"],
    registeredCount: 20,
    maxCapacity: 100,
    status: 'upcoming'
  },
  {
    id: '6',
    title: "光影北大：校园摄影展",
    titleEn: "PKU in Light & Shadow: Photography Exhibition",
    organizer: "Photography Society",
    date: "2024-05-27",
    time: "10:00 - 18:00",
    location: "百周年纪念讲堂 (Centennial Hall)",
    category: ActivityCategory.CULTURE,
    description: "展出百余幅学生摄影作品，记录燕园四季之美。",
    descriptionEn: "Exhibiting 100+ student photos capturing the beauty of Yenching Academy through four seasons.",
    image: "https://picsum.photos/400/250?random=6",
    tags: ["Art", "Exhibition"],
    registeredCount: 80,
    maxCapacity: 500,
    status: 'upcoming'
  },
  {
    id: '7',
    title: "研究生学术论坛：生命科学",
    titleEn: "Graduate Academic Forum: Life Sciences",
    organizer: "School of Life Sciences",
    date: "2024-05-28",
    time: "13:30 - 17:30",
    location: "金光生命科学大楼 (Jinguang Life Sciences Bldg)",
    category: ActivityCategory.ACADEMIC,
    description: "博士生分享最新研究成果，包括基因编辑、神经科学等领域。",
    descriptionEn: "PhD students sharing latest research in gene editing, neuroscience, and more.",
    image: "https://picsum.photos/400/250?random=7",
    tags: ["Academic", "Science"],
    registeredCount: 60,
    maxCapacity: 100,
    status: 'upcoming'
  },
  {
    id: '8',
    title: "国际文化节：美食与音乐",
    titleEn: "International Culture Festival: Food & Music",
    organizer: "International Students Division",
    date: "2024-06-01",
    time: "11:00 - 16:00",
    location: "百讲广场 (Square of Centennial Hall)",
    category: ActivityCategory.CULTURE,
    description: "来自60多个国家的留学生展示家乡美食与歌舞表演。",
    descriptionEn: "International students from 60+ countries showcasing hometown cuisine and performances.",
    image: "https://picsum.photos/400/250?random=8",
    tags: ["Festival", "Food", "Culture"],
    registeredCount: 300,
    maxCapacity: 1000,
    status: 'upcoming'
  },
  {
    id: '9',
    title: "校园十大歌手总决赛",
    titleEn: "Top 10 Campus Singers Final",
    organizer: "Student Union",
    date: "2024-06-05",
    time: "19:00 - 22:00",
    location: "邱德拔体育馆 (Khoo Teck Puat Gym)",
    category: ActivityCategory.CULTURE,
    description: "一年一度的视听盛宴，见证校园歌王的诞生。",
    descriptionEn: "The annual visual and auditory feast, witness the birth of the campus singer king.",
    image: "https://picsum.photos/400/250?random=9",
    tags: ["Music", "Competition", "Entertainment"],
    registeredCount: 2000,
    maxCapacity: 3000,
    status: 'upcoming'
  },
  {
    id: '10',
    title: "北大杯足球赛决赛",
    titleEn: "PKU Cup Football Final",
    organizer: "Sports Department",
    date: "2024-06-10",
    time: "15:00 - 17:00",
    location: "五四体育场 (Wusi Stadium)",
    category: ActivityCategory.SPORTS,
    description: "数学学院队 vs 物理学院队，巅峰对决！",
    descriptionEn: "Math School Team vs Physics School Team, the ultimate showdown!",
    image: "https://picsum.photos/400/250?random=10",
    tags: ["Sports", "Competition", "Football"],
    registeredCount: 400,
    maxCapacity: 800,
    status: 'upcoming'
  },
  {
    id: '11',
    title: "志愿服务：关爱流浪猫",
    titleEn: "Volunteer: Caring for Stray Cats",
    organizer: "Cat Association",
    date: "2024-06-12",
    time: "14:00 - 16:00",
    location: "燕南园 (Yennan Garden)",
    category: ActivityCategory.VOLUNTEER,
    description: "协助协会进行流浪猫投喂、体检与绝育宣传。",
    descriptionEn: "Assist the association with feeding, check-ups, and TNR promotion for stray cats.",
    image: "https://picsum.photos/400/250?random=11",
    tags: ["Volunteer", "Animals", "Love"],
    registeredCount: 15,
    maxCapacity: 20,
    status: 'upcoming'
  },
  {
    id: '12',
    title: "模拟联合国大会",
    titleEn: "Model United Nations Conference",
    organizer: "Model UN Association",
    date: "2024-06-15",
    time: "09:00 - 18:00",
    location: "英杰交流中心 (Yingjie Exchange Center)",
    category: ActivityCategory.ACADEMIC,
    description: "讨论全球气候变化议题，提升外交与演讲能力。",
    descriptionEn: "Discussing global climate change issues, improving diplomatic and speaking skills.",
    image: "https://picsum.photos/400/250?random=12",
    tags: ["Debate", "International", "Academic"],
    registeredCount: 80,
    maxCapacity: 100,
    status: 'upcoming'
  },
  {
    id: '101',
    title: "Campus Marathon 2023",
    organizer: "Sports Dept",
    date: "2023-11-10",
    time: "08:00",
    location: "Campus",
    category: ActivityCategory.SPORTS,
    description: "Annual marathon.",
    image: "https://picsum.photos/400/250?random=101",
    tags: ["Sports"],
    registeredCount: 1000,
    maxCapacity: 1000,
    status: 'completed'
  },
  {
    id: '102',
    title: "Python Workshop",
    organizer: "CS Club",
    date: "2024-03-05",
    time: "14:00",
    location: "Lab 1",
    category: ActivityCategory.ACADEMIC,
    description: "Intro to Python.",
    image: "https://picsum.photos/400/250?random=102",
    tags: ["Tech"],
    registeredCount: 50,
    maxCapacity: 50,
    status: 'completed'
  }
];

export const MOCK_COMMENTS = [
  { id: '1', user: 'User123', content: "Is the calligraphy workshop beginner friendly?", timestamp: "2h ago", likes: 5 },
  { id: '2', user: 'ArtStudent', content: "Yes! The teacher is very patient.", timestamp: "1h ago", likes: 8 },
];